# Generated by Django 5.2.15 on 2026-09-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0227_orderline_price_override_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="desired_delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
